version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: taskapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
    ports:
      - "5432:5432"
    volumes:
      - postgres_/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq
      - redis
      - db
    environment:
      SPRING_PROFILES_ACTIVE=docker
      SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/taskapp
      SPRING_DATASOURCE_USERNAME=postgres
      SPRING_DATASOURCE_PASSWORD=
      SPRING_JPA_HIBERNATE_DDL_AUTO=none
      SPRING_DATA_REDIS_HOST=redis
      SPRING_DATA_REDIS_PORT=6379
      SPRING_RABBITMQ_HOST=rabbitmq
      SPRING_RABBITMQ_PORT=5672
      SPRING_RABBITMQ_USERNAME=guest
      SPRING_RABBITMQ_PASSWORD=

volumes:
  postgres_